name: GitHub Actions Demo
on: [push]
jobs:
  Run-Tests:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v7
      - name: Install bats
        run: |
          git clone --depth 1 --branch v1.14.0 https://github.com/bats-core/bats-core.git
          sudo ./bats-core/install.sh /usr/local
      - name: Run tests
        run: bats ${{ github.workspace }}/tests
