name: GitHub Actions Demo
on: [push]
jobs:
  Run-Tests:
    runs-on: ubuntu-22.04
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Install bats
        run: git clone https://github.com/sstephenson/bats.git && cd bats && ./install.sh $HOME/.local
      - name: Run tests
        run: bats ${{ github.workspace }}/tests